apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: web
spec:
  replicas: 2
  selector: { matchLabels: { app: streamlit } }
  template:
    metadata: { labels: { app: streamlit } }
    spec:
      containers:
        - name: streamlit
          image: football-analytics-prod:latest
          ports: [{ containerPort: 8501 }]
          readinessProbe:
            httpGet: { path: "/", port: 8501 }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 8501 }
            initialDelaySeconds: 15