apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
  namespace: web
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore
  target:
    name: ghcr-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .username }}",
                "password": "{{ .ghcr_pat }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: /github/ghcr_username
    - secretKey: ghcr_pat
      remoteRef:
        key: /github/ghcr_pat
